services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    FooBundle\:
        resource: '../../'
        exclude:
            - '../../DependencyInjection/'
            - '../../Resources/'
            - '../../Tests/'
